name: env1
channels:
  - defaults
  - conda-forge
dependencies:
  - vtk
  - scikit-learn
  - menpo
  - point_cloud_utils
  - cython=0.29.20
  - ipython=8.12
  - ipycanvas
  - ipyevents
  - jupyter_client=7
  - pyzmq=24
  - flask
  - tornado
  - comm=0.1.3
  - tqdm=4.51.0
  - scipy
